package com.fourdfit.app.data.local

import android.content.Context
import com.fourdfit.app.data.api.dto.HoroscopePoolsDto
import com.fourdfit.app.data.api.dto.MockServerState
import com.fourdfit.app.data.api.dto.NutritionPlanDto
import com.fourdfit.app.data.api.dto.WorkoutCatalogDto
import com.google.gson.Gson
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.io.File

/**
 * Reads the bundled seed content (app/src/main/assets/seed, generated by tools/generate_seed.py).
 * Used as the offline fallback before the first successful sync and by the mock API.
 * Call from a background dispatcher — the first access performs disk I/O.
 */
class AssetSeedLoader(
    private val context: Context,
    private val gson: Gson,
) {
    private val workouts: WorkoutCatalogDto by lazy { read("seed/workouts.json", WorkoutCatalogDto::class.java) }
    private val nutrition: NutritionPlanDto by lazy { read("seed/nutrition_30_days.json", NutritionPlanDto::class.java) }
    private val horoscopePools: HoroscopePoolsDto by lazy { read("seed/horoscope_pools.json", HoroscopePoolsDto::class.java) }

    fun workouts(): WorkoutCatalogDto = workouts

    fun nutrition(): NutritionPlanDto = nutrition

    fun horoscopePools(): HoroscopePoolsDto = horoscopePools

    private fun <T> read(
        path: String,
        type: Class<T>,
    ): T =
        context.assets
            .open(path)
            .bufferedReader()
            .use { gson.fromJson(it, type) }
}

/**
 * Simulated server-side storage for mock mode. Lives in noBackupFilesDir and holds only what a
 * real server would return (profile + workout history). Passwords are never stored.
 */
class MockServerStore(
    context: Context,
    private val gson: Gson,
) {
    private val file = File(context.noBackupFilesDir, "mock_server_state.json")
    private val mutex = Mutex()

    suspend fun <T> transact(block: (MockServerState) -> Pair<MockServerState, T>): T =
        mutex.withLock {
            withContext(Dispatchers.IO) {
                val (next, result) = block(readState())
                file.writeText(gson.toJson(next))
                result
            }
        }

    suspend fun read(): MockServerState = mutex.withLock { withContext(Dispatchers.IO) { readState() } }

    private fun readState(): MockServerState {
        if (!file.exists()) return MockServerState(user = null, history = emptyList())
        return runCatching { gson.fromJson(file.readText(), MockServerState::class.java) }.getOrNull()
            ?: MockServerState(user = null, history = emptyList())
    }
}
