"""
Generates the seed content used by the 4D FIT app (offline fallback + mock API)
and by the reference backend. Run from the repo root:

    python3 tools/generate_seed.py

Outputs:
    app/src/main/assets/seed/workouts.json
    app/src/main/assets/seed/nutrition_30_days.json
    app/src/main/assets/seed/horoscope_pools.json
    backend/data/*.json (same files)
"""
import json
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def ex(id, name, cats, diff, muscles, sets, reps, dur, rest, motion, desc, safety, mistakes, tempo="normal"):
    return {
        "id": id, "name": name, "description": desc, "categories": cats, "difficulty": diff,
        "targetMuscles": muscles, "sets": sets, "reps": reps, "durationSeconds": dur,
        "restSeconds": rest, "motion": motion, "tempo": tempo, "safety": safety, "mistakes": mistakes,
    }


EXERCISES = [
    ex("squat", "Bodyweight Squat", ["LOWER_BODY", "FULL_BODY"], "BEGINNER",
       ["Quadriceps", "Glutes", "Hamstrings", "Core"], 3, 12, 36, 45, "SQUAT",
       "A foundational movement that builds leg strength and makes everyday actions like sitting and standing easier.",
       ["Keep your heels on the floor and knees tracking in line with your toes.",
        "Lower only as far as you can while keeping your back neutral.",
        "Stop if you feel sharp pain in your knees, hips or back."],
       ["Letting the knees cave inward", "Rounding the lower back at the bottom", "Shifting weight onto the toes"]),
    ex("jumping_jacks", "Jumping Jacks", ["CARDIO", "FULL_BODY"], "BEGINNER",
       ["Calves", "Shoulders", "Hip abductors", "Heart & lungs"], 3, None, 40, 30, "JUMPING_JACK",
       "A classic full-body warm-up that raises your heart rate and wakes up the shoulders and hips.",
       ["Land softly with slightly bent knees.",
        "For a low-impact version, step one foot out at a time instead of jumping.",
        "Choose a non-slip surface and supportive shoes."],
       ["Landing with locked knees", "Holding your breath", "Letting arms swing loosely without control"], "fast"),
    ex("knee_pushup", "Knee Push-Up", ["UPPER_BODY"], "BEGINNER",
       ["Chest", "Triceps", "Front shoulders", "Core"], 3, 10, 30, 45, "PUSH_UP",
       "A push-up variation with knees down that builds pressing strength while you master form.",
       ["Place a soft mat under your knees.",
        "Keep a straight line from head to knees.",
        "Lower with control; stop if your shoulders or wrists hurt."],
       ["Hips sagging or piking up", "Flaring elbows straight out to the sides", "Dropping the head forward"]),
    ex("forearm_plank", "Forearm Plank", ["CORE"], "BEGINNER",
       ["Deep core", "Shoulders", "Glutes"], 3, None, 30, 30, "PLANK",
       "An isometric hold that trains your core to keep the spine steady and supported.",
       ["Elbows directly under shoulders.",
        "Breathe steadily throughout the hold.",
        "Drop to your knees if your lower back starts to ache."],
       ["Letting the hips sag", "Pushing the hips too high", "Holding the breath"], "slow"),
    ex("glute_bridge", "Glute Bridge", ["LOWER_BODY", "CORE"], "BEGINNER",
       ["Glutes", "Hamstrings", "Lower back"], 3, 15, 45, 40, "GLUTE_BRIDGE",
       "Strengthens the back of the body and supports healthy hips, especially after long periods of sitting.",
       ["Press through your whole foot, not just the toes.",
        "Lift until hips align with knees and shoulders — avoid over-arching.",
        "Keep your neck relaxed on the floor."],
       ["Pushing through the toes", "Arching the lower back at the top", "Rushing the lowering phase"]),
    ex("crunch", "Controlled Crunch", ["CORE"], "BEGINNER",
       ["Rectus abdominis", "Obliques"], 3, 15, 45, 30, "CRUNCH",
       "A small, controlled curl that strengthens the front of the core.",
       ["Support your head lightly; don't pull on your neck.",
        "Keep your lower back in contact with the floor.",
        "Move slowly and exhale as you curl up."],
       ["Yanking the head with the hands", "Using momentum", "Lifting too high off the floor"]),
    ex("cat_cow", "Cat–Cow", ["MOBILITY"], "BEGINNER",
       ["Spine", "Upper back", "Hips"], 2, None, 45, 15, "CAT_COW",
       "A gentle flowing movement that mobilises the whole spine in time with your breath.",
       ["Hands under shoulders, knees under hips.",
        "Move within a comfortable range.",
        "Use a cushion under the knees if needed."],
       ["Moving too quickly", "Forcing the end range", "Locking the elbows"], "slow"),
    ex("side_stretch", "Standing Side Stretch", ["STRETCHING", "MOBILITY"], "BEGINNER",
       ["Obliques", "Lats", "Intercostals"], 2, None, 30, 10, "SIDE_STRETCH",
       "Opens the sides of the body and helps you breathe more freely.",
       ["Keep both feet grounded.",
        "Reach up and over rather than collapsing sideways.",
        "Stop at a gentle stretch, never pain."],
       ["Twisting the torso", "Bouncing into the stretch", "Shrugging the shoulders"], "slow"),
    ex("forward_fold", "Standing Forward Fold", ["STRETCHING"], "BEGINNER",
       ["Hamstrings", "Calves", "Lower back"], 2, None, 30, 10, "FORWARD_FOLD",
       "A calming stretch for the back of the legs and spine.",
       ["Bend your knees as much as you need.",
        "Hinge from the hips and let the head hang.",
        "Roll up slowly to avoid dizziness."],
       ["Locking the knees", "Bouncing", "Standing up too quickly"], "slow"),
    ex("arm_circles", "Arm Circles", ["MOBILITY", "UPPER_BODY"], "BEGINNER",
       ["Shoulders", "Upper back"], 2, None, 30, 15, "ARM_CIRCLES",
       "Warms up the shoulder joints with small, controlled circles in both directions.",
       ["Start with small circles and grow gradually.",
        "Keep your shoulders away from your ears.",
        "Switch direction halfway through."],
       ["Swinging wildly", "Shrugging", "Arching the lower back"], "fast"),
    ex("marching", "Marching in Place", ["CARDIO"], "BEGINNER",
       ["Hip flexors", "Calves", "Heart & lungs"], 3, None, 45, 20, "HIGH_KNEES",
       "A low-impact way to raise your heart rate — perfect for beginners and warm-ups.",
       ["Stand tall and swing the opposite arm.",
        "Land softly on the balls of your feet.",
        "Go at a pace where you can still talk."],
       ["Leaning back", "Looking down", "Stiff arms"], "slow"),
    ex("split_squat", "Static Split Squat", ["LOWER_BODY"], "BEGINNER",
       ["Quadriceps", "Glutes", "Adductors"], 3, 16, 48, 45, "LUNGE",
       "A stable lunge variation that builds single-leg strength and balance.",
       ["Hold a wall or chair for balance if needed.",
        "Lower straight down; keep the front knee over the ankle.",
        "Complete 8 reps on each side."],
       ["Front knee collapsing inward", "Leaning the torso far forward", "Too short a stance"]),
    ex("shoulder_press", "Overhead Press", ["UPPER_BODY"], "INTERMEDIATE",
       ["Shoulders", "Triceps", "Upper back"], 3, 12, 36, 45, "OVERHEAD_PRESS",
       "Press light dumbbells or filled water bottles overhead to build shoulder strength.",
       ["Choose a weight you can lift with full control.",
        "Brace your core and avoid arching the back.",
        "Skip this if you have a shoulder injury."],
       ["Arching the lower back", "Pressing the weights forward", "Locking out aggressively"]),
    ex("pushup", "Push-Up", ["UPPER_BODY", "FULL_BODY"], "INTERMEDIATE",
       ["Chest", "Triceps", "Shoulders", "Core"], 3, 12, 36, 45, "PUSH_UP",
       "The classic bodyweight press that strengthens the chest, arms and core together.",
       ["Hands slightly wider than shoulders.",
        "Body stays in one straight line.",
        "Drop to knee push-ups when form breaks down."],
       ["Hips sagging", "Elbows flaring to 90°", "Half reps"]),
    ex("reverse_lunge", "Reverse Lunge", ["LOWER_BODY"], "INTERMEDIATE",
       ["Quadriceps", "Glutes", "Hamstrings"], 3, 20, 60, 45, "LUNGE",
       "Stepping backward makes lunges knee-friendly while training balance and leg strength.",
       ["Step back far enough that both knees bend to about 90°.",
        "Keep your chest tall.",
        "Complete 10 reps on each leg."],
       ["Front heel lifting", "Wobbling knee", "Slamming the back knee down"]),
    ex("mountain_climbers", "Mountain Climbers", ["CARDIO", "CORE", "FULL_BODY"], "INTERMEDIATE",
       ["Core", "Shoulders", "Hip flexors", "Heart & lungs"], 3, None, 30, 30, "MOUNTAIN_CLIMBER",
       "A dynamic plank that builds core stability and cardio fitness at the same time.",
       ["Keep your hands under your shoulders.",
        "Slow down to keep your hips level.",
        "Place hands on a bench to make it easier."],
       ["Hips bouncing up and down", "Shoulders drifting behind the hands", "Holding the breath"], "fast"),
    ex("high_knees", "High Knees", ["CARDIO"], "INTERMEDIATE",
       ["Hip flexors", "Quads", "Calves", "Heart & lungs"], 3, None, 30, 30, "HIGH_KNEES",
       "Running on the spot with knees driving high — a quick cardio burst.",
       ["Land lightly on the balls of your feet.",
        "Keep your chest up.",
        "March instead of running if you need lower impact."],
       ["Leaning backward", "Landing heavily", "Arms not moving"], "fast"),
    ex("single_leg_bridge", "Single-Leg Glute Bridge", ["LOWER_BODY", "CORE"], "INTERMEDIATE",
       ["Glutes", "Hamstrings", "Core"], 3, 20, 60, 40, "GLUTE_BRIDGE",
       "A unilateral bridge that challenges hip stability and evens out strength between sides.",
       ["Keep hips level as you lift.",
        "Complete 10 reps on each leg.",
        "Return to two legs if you feel cramping."],
       ["Hips tilting", "Over-arching the back", "Pushing through the toes"]),
    ex("bicycle_crunch", "Bicycle Crunch", ["CORE"], "INTERMEDIATE",
       ["Obliques", "Rectus abdominis", "Hip flexors"], 3, 20, 40, 30, "CRUNCH",
       "A rotating crunch that trains the obliques with a smooth pedalling rhythm.",
       ["Rotate from the ribcage, not the elbows.",
        "Keep the movement slow and controlled.",
        "Keep the lower back in contact with the floor."],
       ["Pulling on the neck", "Rushing the reps", "Only moving the elbows"]),
    ex("sumo_squat", "Sumo Squat", ["LOWER_BODY"], "INTERMEDIATE",
       ["Inner thighs", "Glutes", "Quadriceps"], 3, 15, 45, 40, "SQUAT",
       "A wide-stance squat that emphasises the inner thighs and hips.",
       ["Toes turned out slightly, knees follow the toes.",
        "Keep your torso upright.",
        "Only go as low as your hips comfortably allow."],
       ["Knees caving in", "Leaning forward", "Heels lifting"]),
    ex("plank_shoulder_taps", "Plank Shoulder Taps", ["CORE", "UPPER_BODY"], "INTERMEDIATE",
       ["Core", "Shoulders", "Chest"], 3, 20, 40, 30, "SHOULDER_TAP",
       "From a high plank, tap each shoulder while resisting rotation through the hips.",
       ["Widen your feet for more stability.",
        "Move slowly so the hips stay still.",
        "Perform from the knees to make it easier."],
       ["Hips swaying side to side", "Sagging lower back", "Rushing"]),
    ex("hip_flexor_stretch", "Kneeling Hip Flexor Stretch", ["STRETCHING", "MOBILITY"], "BEGINNER",
       ["Hip flexors", "Quadriceps"], 2, None, 60, 10, "LUNGE",
       "Releases tight hips from sitting. Hold 30 seconds on each side.",
       ["Pad the back knee.",
        "Gently tuck the pelvis rather than leaning forward.",
        "Hold a chair for balance if needed."],
       ["Arching the lower back", "Front knee travelling past the toes", "Holding the breath"], "slow"),
    ex("thread_needle", "Thread the Needle", ["MOBILITY"], "INTERMEDIATE",
       ["Thoracic spine", "Shoulders", "Upper back"], 2, None, 40, 15, "CAT_COW",
       "An all-fours rotation that improves upper-back mobility. Alternate sides each rep.",
       ["Keep hips stacked over knees.",
        "Rotate gently and follow your hand with your eyes.",
        "Use a cushion under knees if needed."],
       ["Shifting the hips", "Forcing the rotation", "Collapsing onto the shoulder"], "slow"),
    ex("jump_squat", "Jump Squat", ["LOWER_BODY", "CARDIO", "FULL_BODY"], "ADVANCED",
       ["Quadriceps", "Glutes", "Calves"], 4, 12, 36, 60, "JUMP_SQUAT",
       "An explosive squat that builds power. Only add this once regular squats feel easy.",
       ["Land softly and sink straight into the next squat.",
        "Use a non-slip surface.",
        "Skip jumping if you have knee or ankle problems."],
       ["Landing with stiff legs", "Knees caving on landing", "Losing posture as you tire"], "fast"),
    ex("diamond_pushup", "Diamond Push-Up", ["UPPER_BODY"], "ADVANCED",
       ["Triceps", "Inner chest", "Shoulders"], 4, 10, 30, 60, "PUSH_UP",
       "Hands together under the chest shift the work onto the triceps.",
       ["Keep elbows close to the body.",
        "Maintain a straight line from head to heels.",
        "Widen the hands if your wrists feel strained."],
       ["Flaring elbows", "Sagging hips", "Shortened range"]),
    ex("jump_lunge", "Alternating Jump Lunge", ["LOWER_BODY", "CARDIO"], "ADVANCED",
       ["Quadriceps", "Glutes", "Calves", "Heart & lungs"], 4, 16, 40, 60, "LUNGE",
       "A powerful plyometric lunge that switches legs in the air.",
       ["Master reverse lunges first.",
        "Land softly with control.",
        "Switch to step-back lunges when tired."],
       ["Landing with a straight front leg", "Front knee collapsing", "Torso leaning far forward"], "fast"),
    ex("burpee", "Burpee", ["FULL_BODY", "CARDIO"], "ADVANCED",
       ["Full body", "Heart & lungs"], 4, 10, 50, 60, "BURPEE",
       "Squat, plank, return and stand — a demanding full-body conditioning move.",
       ["Step back instead of jumping to reduce impact.",
        "Keep the core braced in the plank.",
        "Pace yourself and rest whenever you need."],
       ["Sagging hips in the plank", "Landing heavily", "Sacrificing form for speed"]),
    ex("plank_up_down", "Plank Up-Down", ["CORE", "UPPER_BODY"], "ADVANCED",
       ["Core", "Triceps", "Shoulders"], 3, None, 40, 45, "PLANK_UP_DOWN",
       "Move between forearm and high plank while keeping the hips steady.",
       ["Widen the feet to reduce rocking.",
        "Alternate the leading arm.",
        "Perform from the knees to scale it down."],
       ["Hips swinging side to side", "Rushing", "Sagging lower back"]),
    ex("cross_climber", "Cross-Body Mountain Climber", ["CORE", "CARDIO"], "ADVANCED",
       ["Obliques", "Core", "Shoulders", "Heart & lungs"], 4, None, 30, 45, "MOUNTAIN_CLIMBER",
       "Drive each knee toward the opposite elbow to add rotation to the climber.",
       ["Keep shoulders stacked over wrists.",
        "Control the knee drive rather than speeding up.",
        "Slow down if your hips bounce."],
       ["Hips piking up", "Shoulders drifting back", "Short, choppy knee drives"], "fast"),
]

PROGRAMS = [
    ("p_full_body_ignite", "Full Body Ignite", "Whole-body energy boost", ["FULL_BODY"], "BEGINNER",
     "A friendly session that warms you up, strengthens every major muscle group and finishes with a stretch.",
     ["jumping_jacks", "squat", "knee_pushup", "glute_bridge", "forearm_plank", "side_stretch"]),
    ("p_core_matrix", "Core Matrix", "Stability from every angle", ["CORE"], "INTERMEDIATE",
     "Crunch, rotate, brace and climb — a complete core session that ends with spinal mobility.",
     ["crunch", "bicycle_crunch", "forearm_plank", "plank_shoulder_taps", "mountain_climbers", "cat_cow"]),
    ("p_mobility_flow", "Mobility Flow", "Loosen up, move freely", ["MOBILITY", "STRETCHING"], "BEGINNER",
     "A calm flow for shoulders, spine and hips. Great on rest days or after sitting for long periods.",
     ["arm_circles", "cat_cow", "thread_needle", "hip_flexor_stretch", "side_stretch", "forward_fold"]),
    ("p_cardio_pulse", "Cardio Pulse", "Heart-rate intervals", ["CARDIO"], "INTERMEDIATE",
     "Build from marching to high knees with short rests — no equipment needed.",
     ["marching", "jumping_jacks", "high_knees", "mountain_climbers", "sumo_squat", "side_stretch"]),
    ("p_upper_sculpt", "Upper Body Sculpt", "Arms, chest and shoulders", ["UPPER_BODY"], "INTERMEDIATE",
     "Pressing strength and shoulder stability using bodyweight and light weights.",
     ["arm_circles", "pushup", "shoulder_press", "plank_shoulder_taps", "knee_pushup"]),
    ("p_lower_power", "Lower Body Power", "Legs and glutes", ["LOWER_BODY"], "INTERMEDIATE",
     "Squats, lunges and bridges for strong, stable legs, finished with a hip release.",
     ["squat", "reverse_lunge", "sumo_squat", "single_leg_bridge", "hip_flexor_stretch"]),
    ("p_morning_reset", "Morning Reset", "Ten easy minutes to wake up", ["MOBILITY", "STRETCHING"], "BEGINNER",
     "Gentle movement to start the day feeling looser and more alert.",
     ["marching", "arm_circles", "cat_cow", "side_stretch", "forward_fold"]),
    ("p_hybrid_x", "4D Hybrid X", "Advanced power circuit", ["FULL_BODY", "CARDIO"], "ADVANCED",
     "A demanding circuit of plyometrics and strength. Make sure you're comfortable with the intermediate programs first.",
     ["burpee", "jump_squat", "diamond_pushup", "jump_lunge", "plank_up_down", "cross_climber", "forward_fold"]),
]

BREAKFASTS = [
    ("Overnight oats with berries", "Rolled oats soaked in milk or a fortified plant drink, topped with mixed berries and a spoon of chia seeds."),
    ("Veggie scramble on whole-grain toast", "Eggs or tofu scrambled with spinach, tomatoes and peppers, served on whole-grain toast."),
    ("Yogurt parfait", "Plain yogurt layered with sliced fruit, a handful of oats and a sprinkle of nuts."),
    ("Banana and peanut butter toast", "Whole-grain toast with peanut butter, banana slices and a dusting of cinnamon."),
    ("Green breakfast smoothie", "Spinach, banana, frozen mango, yogurt or soy milk and a spoon of oats, blended smooth."),
    ("Savoury oat bowl", "Oats cooked in broth, topped with a soft egg or beans, sautéed mushrooms and herbs."),
    ("Whole-grain breakfast wrap", "A whole-wheat tortilla filled with eggs or black beans, avocado and salsa."),
    ("Cottage cheese and fruit bowl", "Cottage cheese or soy yogurt with pineapple, kiwi and a few pumpkin seeds."),
    ("Apple cinnamon porridge", "Oats simmered with grated apple, cinnamon and a handful of walnuts."),
    ("Avocado and tomato toast", "Smashed avocado on rye or whole-grain bread with tomato slices and a squeeze of lemon."),
    ("Muesli with fruit", "Unsweetened muesli with milk or a plant drink, topped with fresh seasonal fruit."),
    ("Vegetable omelette", "An egg or chickpea-flour omelette with peppers, onion and herbs, plus whole-grain bread."),
    ("Buckwheat pancakes", "Small buckwheat or oat pancakes served with yogurt and berries."),
    ("Chia pudding", "Chia seeds soaked overnight in milk or soy milk, topped with mango and toasted coconut."),
    ("Hummus and egg plate", "Whole-grain pita with hummus, a boiled egg, cucumber and cherry tomatoes."),
]
LUNCHES = [
    ("Quinoa power bowl", "Quinoa with roasted vegetables, chickpeas, leafy greens and a lemon-tahini dressing."),
    ("Grilled chicken or tofu salad", "Mixed greens, grilled chicken or tofu, cucumber, carrots, seeds and an olive-oil dressing."),
    ("Lentil and vegetable soup", "A hearty lentil soup with carrots, celery and tomatoes, served with whole-grain bread."),
    ("Whole-wheat wrap", "Turkey, hummus or falafel with crunchy salad vegetables in a whole-wheat wrap."),
    ("Brown rice stir-fry", "Brown rice with stir-fried vegetables and edamame, prawns or tempeh."),
    ("Mediterranean grain salad", "Bulgur or farro with tomatoes, cucumber, olives, feta or white beans and fresh herbs."),
    ("Bean burrito bowl", "Black beans, brown rice, corn, peppers, salsa and a little avocado."),
    ("Salmon or chickpea sandwich", "Whole-grain bread with salmon or smashed chickpeas, greens and a yogurt-herb spread."),
    ("Minestrone with side salad", "Vegetable and bean minestrone with a simple green salad."),
    ("Nourish bowl", "Sweet potato, greens, quinoa, roasted chickpeas and a ginger-sesame dressing."),
    ("Tuna or white bean pasta salad", "Whole-grain pasta with tuna or white beans, cherry tomatoes, spinach and olive oil."),
    ("Stuffed pita pocket", "Whole-grain pita filled with grilled vegetables, hummus and a protein of your choice."),
    ("Chicken or tofu noodle soup", "A light broth with whole-grain noodles, vegetables and chicken or tofu."),
    ("Rainbow grain bowl", "Barley or brown rice with red cabbage, carrots, edamame, avocado and a citrus dressing."),
    ("Egg and veggie fried rice", "Brown rice stir-fried with egg or tofu, peas, carrots and spring onion."),
]
DINNERS = [
    ("Baked salmon with vegetables", "Oven-baked salmon or marinated tofu with roasted broccoli and new potatoes."),
    ("Chicken and vegetable curry", "A mild tomato-based curry with chicken or chickpeas and vegetables, served with brown rice."),
    ("Bean-rich chilli", "Turkey or lentil chilli with peppers and tomatoes, topped with yogurt and herbs."),
    ("Pasta primavera", "Whole-wheat pasta with seasonal vegetables, olive oil, garlic and a little parmesan."),
    ("Tofu and greens stir-fry", "Tofu or lean beef stir-fried with bok choy, broccoli and mushrooms over soba noodles."),
    ("Sheet-pan chicken and roots", "Chicken thighs or chickpeas roasted with carrots, sweet potato and red onion."),
    ("Fish tacos", "Grilled white fish or beans in corn tortillas with cabbage slaw and lime."),
    ("Vegetable frittata", "Eggs baked with spinach, peppers and onions, served with a mixed salad and bread."),
    ("Lentil bolognese", "A rich lentil and tomato sauce over whole-grain spaghetti with a side salad."),
    ("Stuffed peppers", "Peppers filled with brown rice, beans or lean mince, tomatoes and herbs."),
    ("Grilled fish with herbed quinoa", "Grilled fish or tempeh with herbed quinoa and steamed green beans."),
    ("Chickpea and spinach stew", "Chickpeas simmered with spinach, tomatoes and warm spices, with whole-grain flatbread."),
    ("Homemade veggie pizza", "A whole-wheat base with tomato sauce, plenty of vegetables and a moderate amount of cheese."),
    ("Teriyaki bowl", "Chicken or tofu in a light homemade teriyaki sauce with brown rice, edamame and steamed vegetables."),
    ("Bean and barley bake", "A comforting bake of beans, barley and root vegetables with herbs."),
]
SNACKS = [
    ("Apple with nut butter", "Apple slices with a spoon of peanut or almond butter."),
    ("Hummus and veggie sticks", "Carrot, cucumber and pepper sticks with hummus."),
    ("Small handful of nuts", "A small handful of unsalted mixed nuts."),
    ("Yogurt with berries", "Plain yogurt or a plant alternative with fresh or frozen berries."),
    ("Crackers and cheese", "Whole-grain crackers with a little cheese and cherry tomatoes."),
    ("Banana and almonds", "A banana with a few almonds."),
    ("Roasted chickpeas", "Oven-roasted chickpeas with paprika and a pinch of salt."),
    ("Orange and pumpkin seeds", "An orange with a small sprinkle of pumpkin seeds."),
    ("Steamed edamame", "A bowl of edamame with a squeeze of lime."),
    ("Rice cake with avocado", "A whole-grain rice cake topped with mashed avocado."),
    ("Homemade trail mix", "Unsweetened mix of nuts, seeds and a few raisins."),
    ("Pear and walnuts", "A ripe pear with a few walnut halves."),
    ("Cottage cheese and cucumber", "Cottage cheese or soy yogurt with cucumber slices and black pepper."),
    ("Dates and nuts", "Two dates with a few nuts for a naturally sweet bite."),
    ("Fruit smoothie", "A small smoothie of yogurt or soy milk, berries and half a banana."),
]
HYDRATION = [
    "Start the day with a glass of water before breakfast.",
    "Keep a refillable bottle within reach today.",
    "Add cucumber, lemon or mint to your water for variety.",
    "Have a glass of water with each meal today.",
    "Sip water before and after your workout.",
    "Herbal teas count toward your fluids — enjoy one this afternoon.",
    "Set three mini check-ins today: morning, midday and afternoon.",
    "Feeling tired? Try a glass of water and a short walk.",
    "Water-rich foods like cucumber, oranges and watermelon help too.",
    "Swap one sugary drink for sparkling water today.",
]
WELLNESS_TIPS = [
    "Take a 10-minute walk after a meal today.",
    "Stand up and stretch for one minute every hour you sit.",
    "Try five slow breaths — in for four, out for six — when you feel rushed.",
    "Aim for a consistent bedtime tonight.",
    "Spend a few minutes outside in daylight this morning.",
    "Put your phone away during one meal and eat slowly.",
    "Write down one thing you're grateful for.",
    "Take the stairs once today if you can.",
    "Do a 5-minute stretch before bed.",
    "Message a friend or family member you haven't spoken to lately.",
    "Notice your posture — relax your shoulders away from your ears.",
    "Plan tomorrow's meals so healthy choices are easy.",
    "Give your eyes a break: look at something far away for 20 seconds.",
    "Celebrate a small win from this week.",
    "Try a new vegetable or fruit this week.",
    "Rest is part of training — enjoy a lighter movement day if you need it.",
    "Unplug from screens 30 minutes before bed.",
    "Take a mindful minute: notice five things you can see.",
    "Prepare a healthy snack in advance for the afternoon.",
    "Go for a walk with someone and chat.",
    "Tidy one small space — a calm environment can feel restful.",
    "Listen to a favourite song and move to it.",
    "Check in with your energy: what helped today?",
    "Stretch your hips and hamstrings after long sitting.",
    "Practise saying no to one thing that drains you.",
    "Try a short body scan before sleep.",
    "Cook one meal at home this week with a friend or family member.",
    "Spend time on a hobby that makes you lose track of time.",
    "Reflect on how far you've come since Day 1.",
    "Plan how you'll keep moving after this 30-day plan — consistency beats intensity.",
]
NUTRITION_TIPS = [
    "Fill half your plate with vegetables or salad.",
    "Choose whole grains like oats, brown rice or whole-wheat bread more often.",
    "Include a protein source at every meal — beans, eggs, fish, tofu, dairy or lean meat.",
    "Eat a variety of colourful fruits and vegetables across the week.",
    "Healthy fats from nuts, seeds, olive oil and avocado support a balanced diet.",
    "Regular meals can help keep your energy steady through the day.",
    "Read food labels to spot added sugars and salt.",
    "Frozen fruits and vegetables are convenient and just as useful.",
    "Pulses like lentils and chickpeas are budget-friendly sources of protein and fibre.",
    "Keep easy healthy snacks on hand, like fruit, yogurt or nuts.",
    "Herbs, spices and citrus add flavour without extra salt.",
    "Eat slowly and pause mid-meal to notice how hungry you still are.",
    "Batch-cook grains and beans to make balanced meals quicker.",
    "Enjoy treats mindfully — balance matters more than perfection.",
    "Oily fish once or twice a week is a common recommendation; plant eaters can use seeds and walnuts.",
    "Include a fruit or vegetable with breakfast.",
    "Pair carbohydrates with protein and fibre for longer-lasting energy.",
    "Plan a simple shopping list around the meals in your plan.",
    "If you have allergies or a medical condition, adapt meals with a registered dietitian.",
    "Listen to hunger and fullness cues rather than strict rules.",
]

ELEMENT_OPENERS = {
    "Fire": [
        "Your natural spark is easy to notice today.",
        "Enthusiasm comes easily, so channel it into something you enjoy.",
        "A bold, playful mood colours the day.",
        "Your energy is high — pace it so it lasts.",
        "Today rewards courage in small, everyday choices.",
    ],
    "Earth": [
        "Steady routines feel especially satisfying today.",
        "Your practical side shines; small actions add up.",
        "Grounding habits help you feel at your best.",
        "Patience is your quiet strength today.",
        "A calm, methodical approach suits the day.",
    ],
    "Air": [
        "Curiosity leads you somewhere interesting today.",
        "Conversations flow easily — share an idea.",
        "A fresh perspective makes a familiar task more fun.",
        "Your mind is buzzing; jot your thoughts down.",
        "Lightness and humour carry you through the day.",
    ],
    "Water": [
        "Your intuition feels clear and gentle today.",
        "Kindness toward yourself sets a warm tone.",
        "Quiet moments help you recharge.",
        "You may feel especially connected to people close to you.",
        "Creativity flows when you give it some space.",
    ],
}
GENERAL = [
    "It's a good day to try something slightly outside your comfort zone, like a new route for your walk.",
    "Small, consistent steps feel more rewarding than big leaps right now.",
    "Someone may appreciate your encouragement more than you expect.",
    "Clearing one small task early could free your mind for the rest of the day.",
    "A short break outdoors might bring a new idea.",
    "Plans may shift a little — staying flexible keeps things light.",
    "Focus on progress, not perfection, in whatever you take on.",
    "A favourite song or playlist could lift your mood at the right moment.",
    "Sharing a meal or a chat could be the highlight of your day.",
    "Your attention to detail helps something come together nicely.",
    "Take a moment to notice what's going well — there's more than you think.",
    "Learning something new, even for ten minutes, feels satisfying today.",
    "A tidy space might help you feel more focused.",
    "It's a nice day to reconnect with a hobby you've missed.",
    "Saying yes to rest is just as valuable as saying yes to activity.",
    "Your sense of humour makes an ordinary moment memorable.",
    "Look for the simple version of a task; it may be all you need.",
    "Gratitude for small things sets a positive tone for the evening.",
    "Trying a new recipe or ingredient could be fun.",
    "A thoughtful message could brighten someone's day — and yours.",
]
MOTIVATION = [
    "Show up for five minutes; momentum will often do the rest.",
    "Every rep is a vote for the person you're becoming.",
    "Consistency beats intensity — keep the streak gentle and real.",
    "Your only comparison is who you were yesterday.",
    "Progress loves patience.",
    "Strong is built one ordinary day at a time.",
    "Move because you care about yourself, not to punish yourself.",
    "Celebrate effort, not just outcomes.",
    "Small wins stacked together become big change.",
    "Breathe, focus, begin.",
    "Rest is part of the plan, not a break from it.",
    "You don't have to feel ready to start — starting helps you feel ready.",
    "Energy grows when you use it well.",
    "Today counts, even if it's a lighter day.",
    "Keep it simple: water, movement, rest, repeat.",
    "Your future self will thank you for today's effort.",
    "Discipline is remembering what you want most.",
    "Done is better than perfect.",
    "Be proud of how far you've already come.",
    "Find the joy in moving your body.",
]
WELLNESS = [
    "Try a short walk after lunch to stretch your legs.",
    "Keep water nearby and sip regularly.",
    "A few minutes of stretching tonight could help you unwind.",
    "Take three slow, deep breaths before your next task.",
    "Step outside for some daylight if you can.",
    "Give your eyes a screen break every hour.",
    "A balanced snack with protein and fruit can keep energy steady.",
    "Wind down with a calm routine before bed.",
    "Check your posture and relax your shoulders.",
    "Mobility work for hips and back feels great today.",
    "Choose a colourful vegetable with dinner.",
    "Laughing with a friend is good for the mood.",
    "Plan a gentle movement session if you're feeling tired.",
    "Write down one thing you're looking forward to.",
    "A tidy, quiet space can help you relax.",
    "Listen to your body and rest when you need to.",
    "Stretch your calves and hamstrings after sitting.",
    "Try a 5-minute mindfulness pause.",
    "Prepare tomorrow's water bottle tonight.",
    "Enjoy your meals without distractions today.",
]
COLORS = [
    {"name": "Electric blue", "hex": "#3D7BFF"}, {"name": "Neon violet", "hex": "#8B6CFF"},
    {"name": "Aqua", "hex": "#22E4FF"}, {"name": "Mint", "hex": "#3DF5B0"},
    {"name": "Sunset orange", "hex": "#FF8A4C"}, {"name": "Magenta", "hex": "#FF5AD9"},
    {"name": "Gold", "hex": "#FFC15A"}, {"name": "Coral", "hex": "#FF6F7D"},
    {"name": "Emerald", "hex": "#21C47B"}, {"name": "Sky", "hex": "#7FD3FF"},
    {"name": "Lavender", "hex": "#B9A6FF"}, {"name": "Silver", "hex": "#C9CFDD"},
    {"name": "Ruby", "hex": "#E0315B"}, {"name": "Turquoise", "hex": "#1FC8C8"},
]


def program_minutes(ex_ids, by_id):
    total = 5
    for i, eid in enumerate(ex_ids):
        e = by_id[eid]
        total += e["sets"] * e["durationSeconds"]
        rests = e["sets"] if i < len(ex_ids) - 1 else e["sets"] - 1
        total += rests * e["restSeconds"]
    return max(1, math.ceil(total / 60))


def build():
    by_id = {e["id"]: e for e in EXERCISES}
    programs = []
    for pid, title, subtitle, cats, diff, desc, ids in PROGRAMS:
        for i in ids:
            assert i in by_id, i
        programs.append({
            "id": pid, "title": title, "subtitle": subtitle, "description": desc, "categories": cats,
            "difficulty": diff, "exerciseIds": ids, "estimatedMinutes": program_minutes(ids, by_id),
        })
    workouts = {"version": 1, "exercises": EXERCISES, "programs": programs}

    days = []
    for d in range(1, 31):
        i = d - 1
        second_half = d > 15
        b = BREAKFASTS[i % 15]
        l = LUNCHES[(i + (5 if second_half else 0)) % 15]
        dn = DINNERS[(i + (9 if second_half else 0)) % 15]
        s = SNACKS[(i * 2 + (3 if second_half else 0)) % 15]
        days.append({
            "day": d,
            "breakfast": {"title": b[0], "description": b[1]},
            "lunch": {"title": l[0], "description": l[1]},
            "dinner": {"title": dn[0], "description": dn[1]},
            "snack": {"title": s[0], "description": s[1]},
            "hydration": HYDRATION[i % len(HYDRATION)],
            "wellnessTip": WELLNESS_TIPS[i],
            "nutritionTip": NUTRITION_TIPS[i % len(NUTRITION_TIPS)],
        })
    combos = {(x["breakfast"]["title"], x["lunch"]["title"], x["dinner"]["title"], x["snack"]["title"]) for x in days}
    assert len(combos) == 30
    nutrition = {
        "version": 1,
        "disclaimer": "General wellness guidance only — not medical or dietary advice. Adapt meals to allergies, preferences and needs.",
        "days": days,
    }
    pools = {
        "version": 1,
        "elementOpeners": ELEMENT_OPENERS, "general": GENERAL, "motivation": MOTIVATION,
        "wellness": WELLNESS, "colors": COLORS,
    }
    out = {"workouts.json": workouts, "nutrition_30_days.json": nutrition, "horoscope_pools.json": pools}
    for folder in ["app/src/main/assets/seed", "backend/data/seed"]:
        path = os.path.join(ROOT, folder)
        os.makedirs(path, exist_ok=True)
        for name, data in out.items():
            with open(os.path.join(path, name), "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
    print("exercises:", len(EXERCISES), "programs:", [(p["id"], p["estimatedMinutes"]) for p in programs])


if __name__ == "__main__":
    build()
